import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
import ReduxProvider from "@/store/provider";
import { ThemeProvider } from "@/components/theme-provider";
import ModeToggle from "@/components/theme-toggle";
import Head from "next/head";
import React from "react";

export const metadata: Metadata = {
  title: "Comece aqui",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // <html lang="en" className="scroll-smooth hover:scroll-auto">
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <div id="fb-root"></div>
        <Head>
          <div id="fb-root" key={1}></div>
          <script
            key={2}
            async
            defer
            crossOrigin="anonymous"
            src="https://connect.facebook.net/pt_BR/sdk.js#xfbml=1&version=v18.0&appId=2070160319877660"
            nonce="eXN6Y0cH"
          ></script>
        </Head>
        <ReduxProvider>
          <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
            {/* <div className="fixed right-0">
              <ModeToggle />
            </div> */}
            {children}
          </ThemeProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
