import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
import ReduxProvider from "@/store/provider";
import { ThemeProvider } from "@/components/theme-provider";
import ModeToggle from "@/components/theme-toggle";

export const metadata: Metadata = {
  title: "Comece aqui",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // <html lang="en" className="scroll-smooth hover:scroll-auto">
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
            {/* <div className="fixed right-0">
              <ModeToggle />
            </div> */}
            {children}
          </ThemeProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
