name: CARLITOS CI
on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Repositorio
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          #cache: ${{ steps.detect-package-manager.outputs.manager }}
      - run: npm install -g yarn
      #- run: CI=false
      - run: yarn install --frozen-lockfile
      - run: yarn build
      
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        #uses: actions/deploy-pages@v4
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          #ARGS: "-rltgoDzvO --delete"
          #ARGS: "-rlgoDzvc -i --delete"
          #ARGS: "-rlgoDzvc -i"
          #ARGS: "-avzr --delete"
          SOURCE: "/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          #TARGET: ${{ secrets.REMOTE_TARGET }}
          TARGET: /www/wwwroot/evnt.carlosdj.com.br/

      - name: Post Deploy
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.REMOTE_HOST }}
            username: ${{ secrets.REMOTE_USER }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            port: ${{ secrets.REMOTE_PORT }}
            script: | 
              cd /www/wwwroot/evnt.carlosdj.com.br/
              yarn
              yarn build 
              yarn pm2:restart
              
      
    