name: CARLITOS CI
on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Repositorio
        uses: actions/checkout@v1

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      #- run: npm install --global yarn
      #- run: CI=false
      #- run: yarn install
      #- run: yarn build

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          #ARGS: "-rltgoDzvO --delete"
          ARGS: "-rltDzvO --delete"
          #ARGS: "-rlgoDzvc --delete"
          #ARGS: "-rlgoDzvc -i"
          #ARGS: "-avzr --delete"
          SOURCE: "/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          #TARGET: ${{ secrets.REMOTE_TARGET }}
          TARGET: /www/wwwroot/evnt.carlosdj.com.br/

      - name: Post Deploy
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.REMOTE_HOST }}
            username: ${{ secrets.REMOTE_USER }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            port: ${{ secrets.REMOTE_PORT }}
            script: | 
              cd /www/wwwroot/evnt.carlosdj.com.br/
              yarn 
              yarn build
              yarn pm2:restart
      
    